import type { Metadata } from "next";
import { Fugaz_One } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const fugazOne = Fugaz_One({
  variable: "--font-fugaz-one",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={fugazOne.className}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
